config/routes.rb
Rails.application.routes.draw do
    root 'arenas#index'
    resources :arenas, only: [:index]
    resources :characters
    resources :battles
    resources :weapons
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    has_many :inventories
    has_many :characters, through: :inventories
    include SharedSearchMethods
end

app/controllers/weapons_controller.rb
class WeaponsController < AdminsController

    private

    def weapon_params
        params.require(:weapon).permit(:name,
                                          :detail,
                                          :power,
                                          :type)
    end

end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_fields.html.erb
 <div class="box-body">

  <div class="form-group col-xs-12">
    <%= f.label :name, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class:"form-control", disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :power, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :power, class:"form-control", max: 6, min: 1, disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :shield, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.check_box :shield, class:"form" , disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :detail, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :detail, class:"form-control", disabled: fields_disabled %>
    </div>
  </div>

</div>

<div class="box-footer">
  <%= f.submit 'Submit', :class => 'btn btn-success pull-right' if !fields_disabled %>
</div>

app/views/weapons/edit.html.erb
<div class="box box-info">
  <%= render 'layouts/admin/table_header' %>
  <%= form_for @weapon, url: weapon_path(@weapon) do |f| %>

    <% if @weapon.errors.any? %>
      <div class="alert form-errors form-group">
        <button type="button" class="close" name="button" data-dismiss="alert" aria-hideen="true"> ×</button>
        <% @weapon.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </div>
    <% end %>
    <%= render 'fields', f: f, weapon: @weapon, fields_disabled: false, type_hidden: "" %>

  <% end %>
</div>

app/views/weapons/index.html.erb
<div class="row p-15">
  <%= search_form %>
  <%= link_to  new_weapon_path, class: 'btn  btn-success pull-right' do %>
    New <i class="fa fa-plus"></i>
  <%- end %>
</div>

<div class="box box-info">
  <div class="box">
    <%= render 'layouts/admin/table_header' %>
    <%= collection_table_for @weapons, [:id, :name, :actions] do |row, weapon| %>
      <%- row.column(:id) { (weapon.id.to_s) } %>
      <%- row.column(:name) { (weapon.name) } %>
      <%- row.column(:actions) do %>
        <div class="btn-group btn-group-sm">
          <%= link_to weapon_path(weapon), class: 'btn btn-sm btn-icon btn-default' do %>
            <i class="fa fa-eye"></i>
          <%- end %>
        </div>
        <div class="btn-group btn-group-sm">
          <%= link_to  edit_weapon_path(weapon), class: 'btn btn-sm btn-icon btn-default  btn-default' do %>
            <i class="fa fa-pencil"></i>
          <%- end %>
        </div>

        <div class="btn-group btn-group-sm">
          <%= link_to  weapon_path(weapon), method: :delete, class: 'btn btn-sm btn-icon btn-danger tooltips', 'data-confirm' => 'Sure ?', 'data-placement' => 'bottom' do %>
            <i class='fa fa-trash-o'></i>
          <%- end %>
        </div>
      <%- end %>
    <% end %>
  </div>
</div>

app/views/weapons/new.html.erb
<div class="box box-info">
  <%= render 'layouts/admin/table_header' %>
  <%= form_for @weapon do |f| %>

    <% if @weapon.errors.any? %>
      <div class="alert form-errors form-group">
        <button type="button" class="close" name="button" data-dismiss="alert" aria-hideen="true"> ×</button>
        <% @weapon.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </div>
    <% end %>
    <%= render 'fields', f: f, weapon: @weapon, fields_disabled: false, type_hidden: "" %>

  <% end %>
</div>

app/views/weapons/show.html.erb
<div class="box box-info">
  <div class='disable_input'>
  <%= render 'layouts/admin/table_header' %>

  <%= form_for @weapon, url: weapon_path(@weapon) do |f| %>

   <div class="box-body">
    <div class="form-group col-xs-12">
    <%= f.label :id, class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= @weapon.id %>
      </div>
    </div>
   </div>
  
    <%= render 'fields', f: f, weapon: @weapon, fields_disabled: true, type_hidden: "hidden" %>

  <% end %>
 </div>
</div>