config/routes.rb
Rails.application.routes.draw do
    root 'arenas#index'
    resources :arenas, only: [:index]
    resources :characters
    resources :battles
    resources :weapons
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :inventories
    has_many :weapons, through: :inventories
    include SharedSearchMethods
    has_attached_file :avatar, styles: { thumb: "120x120>" }, default_url: "/images/:style/missing.jpg"
    validates_attachment_content_type :avatar, content_type: ["image/jpeg", "image/gif", "image/png"], size: { in: 0..10.kilobytes }
end

app/controllers/characters_controller.rb
class CharactersController < AdminsController
    before_action :set_default_instances_variables, only: [:new, :show, :create, :edit, :update]

    private

    def character_params
        params.require(:character).permit(:name,
                                          :hp,
                                          :attack,
                                          :armor,
                                          :weapon_ids,
                                          :level,
                                          :exp,
                                          :avatar,
                                          :win_count,
                                          :lose_count,
                                          :background)
    end

    def set_default_instances_variables
        @weapons = Weapon.all
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_fields.html.erb
 <div class="box-body">


  <div class="form-group col-xs-12">
    <%= f.label :name, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class:"form-control", disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :hp, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :hp, class:"form-control", max: 10, min: 1, disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :attack, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :attack, class:"form-control", max: 6, min: 1, disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :armor, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :armor, class:"form-control", max: 6, min:1, disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :background, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :background, class:"form-control", disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :weapons, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.select(:weapon_ids, @weapons.collect {|a| [a.name, a.id]}, {:prompt => "Please select"}, id: "select_weapon_ids", class: "select2 full-width", :multiple => true, :size => 3) %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :level, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :level, class:"form-control", min: 1, disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :exp, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :exp, class:"form-control", disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :win_count, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :win_count, class:"form-control", disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :lose_count, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :lose_count, class:"form-control", disabled: fields_disabled %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :avatar, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
        <% if params[:action] == 'show'%>
            <%= image_tag @character.avatar.url(:thumb) %>
        <% else%>
            <%= f.file_field :avatar %>
        <% end %>
    </div>
  </div>

</div>

<div class="box-footer">
  <%= f.submit 'Submit', :class => 'btn btn-success pull-right' if !fields_disabled %>
</div>

app/views/characters/edit.html.erb
<div class="box box-info">
  <%= render 'layouts/admin/table_header' %>
  <%= form_for @character, url: character_path(@character) do |f| %>

    <% if @character.errors.any? %>
      <div class="alert form-errors form-group">
        <button type="button" class="close" name="button" data-dismiss="alert" aria-hideen="true"> ×</button>
        <% @character.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </div>
    <% end %>
    <%= render 'fields', f: f, character: @character, fields_disabled: false, type_hidden: "" %>

  <% end %>
</div>

app/views/characters/index.html.erb
<div class="row p-15">
  <%= search_form %>
  <%= link_to  new_character_path, class: 'btn  btn-success pull-right' do %>
    New <i class="fa fa-plus"></i>
  <%- end %>
</div>

<div class="box box-info">
  <div class="box">
    <%= render 'layouts/admin/table_header' %>
    <%= collection_table_for @characters, [:id, :name, :actions] do |row, character| %>
      <%- row.column(:id) { (character.id.to_s) } %>
      <%- row.column(:name) { (character.name) } %>
      <%- row.column(:actions) do %>
        <div class="btn-group btn-group-sm">
          <%= link_to character_path(character), class: 'btn btn-sm btn-icon btn-default' do %>
            <i class="fa fa-eye"></i>
          <%- end %>
        </div>
        <div class="btn-group btn-group-sm">
          <%= link_to  edit_character_path(character), class: 'btn btn-sm btn-icon btn-default  btn-default' do %>
            <i class="fa fa-pencil"></i>
          <%- end %>
        </div>

        <div class="btn-group btn-group-sm">
          <%= link_to  character_path(character), method: :delete, class: 'btn btn-sm btn-icon btn-danger tooltips', 'data-confirm' => 'Sure ?', 'data-placement' => 'bottom' do %>
            <i class='fa fa-trash-o'></i>
          <%- end %>
        </div>
      <%- end %>
    <% end %>
    <div class="pull-right">
      <!--%= paginate @boxes, theme: 'twitter-bootstrap-3' %-->
    </div>
  </div>
</div>

app/views/characters/new.html.erb
<div class="box box-info">
  <%= render 'layouts/admin/table_header' %>
  <%= form_for @character do |f| %>

    <% if @character.errors.any? %>
      <div class="alert form-errors form-group">
        <button type="button" class="close" name="button" data-dismiss="alert" aria-hideen="true"> ×</button>
        <% @character.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </div>
    <% end %>
    <%= render 'fields', f: f, character: @character, fields_disabled: false, type_hidden: "" %>

  <% end %>
</div>

app/views/characters/show.html.erb
<div class="row p-15">
  
</div>

<div class="box box-info">
  <div class='disable_input'>
  <%= render 'layouts/admin/table_header' %>

  <%= form_for @character, url: character_path(@character) do |f| %>

   <div class="box-body">
    <div class="form-group col-xs-12">
    <%= f.label :id, class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= @character.id %>
      </div>
    </div>
   </div>
  
    <%= render 'fields', f: f, character: @character, fields_disabled: true, type_hidden: "hidden" %>

  <% end %>
 </div>
</div>