config/routes.rb
Rails.application.routes.draw do
    root 'arenas#index'
    resources :arenas, only: [:index]
    resources :characters
    resources :battles
    resources :weapons
end

app/models/battle.rb
class Battle < ApplicationRecord
    include SharedSearchMethods
end

app/controllers/battles_controller.rb
class BattlesController < AdminsController
    before_action :set_default_instances_variables, only: [:new, :show, :create, :edit, :update]

    def create
        @battle = Battle.new(battle_params)
        if battle_params['player_one_id'] == battle_params['player_two_id']
            @battle.errors[:base] << ("ERROR: The player can't fight with himself.")
            render :new
        end
        super
    end

    private

    def battle_params
        params.require(:battle).permit(:player_one_id,
                                       :player_two_id,
                                       :historic,
                                       :winner_id,
                                       :turn)
    end

    def set_default_instances_variables
        @characters = Character.all
    end
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/battles/_fields.html.erb
 <div class="box-body">

  <div class="form-group col-xs-12">
    <%= f.label :player_one, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:player_one_id, @characters, :id, :name, {:include_blank => 'Select the first player'}, class:"form-control select2 full-width", disabled: fields_disabled) %>
    </div>
  </div>

  <div class="form-group col-xs-12">
    <%= f.label :player_two, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:player_two_id, @characters, :id, :name, {:include_blank => 'Select the second player'}, class:"form-control select2 full-width", disabled: fields_disabled) %>
    </div>
  </div>

</div>

<div class="box-footer">
  <%= f.submit 'Submit', :class => 'btn btn-success pull-right' if !fields_disabled %>
</div>

app/views/battles/edit.html.erb
<div class="box box-info">
  <%= render 'layouts/admin/table_header' %>
  <%= form_for @battle, url: battle_path(@battle) do |f| %>

    <% if @battle.errors.any? %>
      <div class="alert form-errors form-group">
        <button type="button" class="close" name="button" data-dismiss="alert" aria-hideen="true"> ×</button>
        <% @battle.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </div>
    <% end %>
    <%= render 'fields', f: f, battle: @battle, fields_disabled: false, type_hidden: "" %>

  <% end %>
</div>

app/views/battles/index.html.erb
<div class="row p-15">
  <%= search_form %>
  <%= link_to  new_battle_path, class: 'btn  btn-success pull-right' do %>
    New <i class="fa fa-plus"></i>
  <%- end %>
</div>

<div class="box box-info">
  <div class="box">
    <%= render 'layouts/admin/table_header' %>
    <%= collection_table_for @battles, [:id, :battle, :actions] do |row, battle| %>
      <%- row.column(:id) { (battle.id.to_s) } %>
      <%- row.column(:battle) do %>
          <% if battle.winner_id%>
            Winner: <%= Character.find(battle.winner_id).name %>
        <% else %>
            <div class="btn-group btn-group-sm">
                <%= link_to arenas_path(battle_id: battle.id), :controller => "searches", :query => "ruby on rails", class: 'btn btn-sm btn-icon btn-default' do %>
                    Fight
                <%- end %>
            </div>
          <% end %>
      <%- end%>
      <%- row.column(:actions) do %>
        <div class="btn-group btn-group-sm">
          <%= link_to battle_path(battle), class: 'btn btn-sm btn-icon btn-default' do %>
            <i class="fa fa-eye"></i>
          <%- end %>
        </div>
        <div class="btn-group btn-group-sm">
          <%= link_to  battle_path(battle), method: :delete, class: 'btn btn-sm btn-icon btn-danger tooltips', 'data-confirm' => 'Sure ?', 'data-placement' => 'bottom' do %>
            <i class='fa fa-trash-o'></i>
          <%- end %>
        </div>
      <%- end %>
    <% end %>
  </div>
</div>

app/views/battles/new.html.erb
<div class="box box-info">
  <%= render 'layouts/admin/table_header' %>
  <%= form_for @battle do |f| %>

    <% if @battle.errors.any? %>
      <div class="alert form-errors form-group">
        <button type="button" class="close" name="button" data-dismiss="alert" aria-hideen="true"> ×</button>
        <% @battle.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </div>
    <% end %>
    <%= render 'fields', f: f, battle: @battle, fields_disabled: false, type_hidden: "" %>

  <% end %>
</div>

app/views/battles/show.html.erb
<div class="row p-15">
  
</div>

<div class="box box-info">
  <div class='disable_input'>
  <%= render 'layouts/admin/table_header' %>

  <%= form_for @battle, url: battle_path(@battle) do |f| %>

   <div class="box-body">
    <div class="form-group col-xs-12">
    <%= f.label :id, class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= @battle.id %>
      </div>
    </div>
   </div>
  
    <%= render 'fields', f: f, battle: @battle, fields_disabled: true, type_hidden: "hidden" %>

  <% end %>
 </div>
</div>